#!/bin/bash
if [[ $# -gt 1 ]]; then
	echo "$0: error - to many arguments - use only 1 argument" >&2
	exit 1
elif [[ ! -r $1 ]]; then
	echo "$0: file doesn't exist: \`$1'" >&2
	exit 1
else
	xdg-open "$1" > /dev/null 2>&1 & disown
fi
exit 0